version: '3.7'
services:

  lnk:
    image: lnk_dev
    container_name: lnk_dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MODE=dev
    environment:
      - REDIS_HOST=redis
      - TOKEN=token
      - CLIPPER_URL=
      - CLIPPER_TOKEN=
    command: /usr/share/python3/app/bin/python main.py
    ports:
      - "8010:8010"
    volumes:
      - ./app/:/home/app/app/
    logging:
        driver: json-file
        options:
            max-size: "10m"
            max-file: "5"

  redis:
    image: "redis:6.0.15-alpine"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"